name: Cloud Infrastructure CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: ./azure-terraform-ansible-lab
        run: terraform fmt -check

      - name: Terraform Initialise
        working-directory: ./azure-terraform-ansible-lab
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./azure-terraform-ansible-lab
        run: terraform validate

      - name: Build Docker Image
        run: |
          docker build \
            -t cloud-ci-test:latest \
            ./docker-kubernetes-microservices-lab/docker

      - name: Install kubeconform
        run: |
          curl -L -o kubeconform.tar.gz \
            https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz

          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes Manifests
        run: |
          kubeconform \
            -strict \
            -summary \
            ./docker-kubernetes-microservices-lab/kubernetes/*.yaml
